version: '3.8'

services:
  chiaro-db:
    image: postgres:15-alpine
    container_name: chiaro_db
    environment:
      - POSTGRES_DB=chiaro
      - POSTGRES_USER=chiaro_user
      - POSTGRES_PASSWORD=chiaro_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: